#!/bin/bash

#########################################
### K3ai (keɪ3ai) Plugins - Install Template
### https://github.com/kf5i/k3ai
### Alessandro Festa @bringyourownai
### Gabriele Santomaggio @gsantomaggio
######################################### 

### do not change this setion ###
info()
{
    echo '[INFO] ' "$@"
}

infoL()
{
    echo -en '[INFO] ' "$@\n"
}

sleep_cursor()
{
 chars="/-\|"
 for (( z=0; z<7; z++ )); do
   for (( i=0; i<${#chars}; i++ )); do
    sleep 0.5
    echo -en "${chars:$i:1}" "\r"
  done
done
}


wait() 
{
status=1
infoL "Testing.." $1.$2  
while [ : ]
  do
    sleep_cursor &
    kubectl wait --for condition=available --timeout=14s deploy -l  $1   -n $2
    status=$?
    
    if [ $status -ne 0 ]
    then 
      infoL "$1 isn't ready yet. This may take a few minutes..."
      sleep_cursor
    else
      break  
    fi 
  done
}

#######
### Kubeflow pipelines login as example, change it accordingly with your needs
 k3s kubectl create ns jupyter
    k3s kubectl apply -f - << EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-minimal
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-srv
  template:
    metadata:
      labels:
        app: jupyter-srv
    spec:
      containers:
      - name: jupyter-minimal
        image: jupyter/minimal-notebook
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: jupyter
EOF
    k3s kubectl apply -f - << EOF
apiVersion: v1
kind: Service
metadata:
  name: jupyter-minimal-service
  namespace: tf-serving
spec:
  selector:
    app: jupyter-srv
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
  type: LoadBalancer
EOF

    waiting_pod_array=("k8s-app=kube-dns;kube-system" 
                       "k8s-app=metrics-server;kube-system"
                       "app=traefik;kube-system"
                       "app=jupyter-srv;jupyter")

    for i in "${waiting_pod_array[@]}"; do 
      echo "$i"; 
      IFS=';' read -ra VALUES <<< "$i"
        wait "${VALUES[0]}" "${VALUES[1]}"
    done


    info "Tensorflow Serving ready!!"

    info "Defining the ingress"
    sleep_cursor

    k3s kubectl apply -f - << EOF
      apiVersion: networking.k8s.io/v1beta1
      kind: IngressClass
      metadata: 
        name: traefik-lb
      spec: 
        controller: traefik.io/ingress-controller
EOF

    k3s kubectl apply -f - << EOF
      apiVersion: "networking.k8s.io/v1beta1"
      kind: "Ingress"
      metadata:
        name: "tf-serving-ingress"
        namespace: tf-serving
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
          
      spec:
        ingressClassName: "traefik-lb"
        rules:
        - http:
            paths:
            - path: "/"
              backend:
                serviceName: "jupyter-minimal-serving"
                servicePort: 8888
EOF

sleep_cursor

IP=$(kubectl get service/traefik -o jsonpath='{.status.loadBalancer.ingress[0].ip}' -n kube-system)
info "pipelines UI: http://"$IP 
}

install

#######
