plugin-name: kubeflow-pipelines
namespace: "kubeflow"
yaml:
  - url: "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=1.6.0"
    type: "kustomize"

  - url: "github.com/kubeflow/pipelines/manifests/kustomize/env/platform-agnostic-pns?ref=1.6.0"
    type: "kustomize"



    
    
    
    
