#!/bin/bash

#########################################
### K3ai (keɪ3ai) Plugins - Install Template
### https://github.com/kf5i/k3ai
### Alessandro Festa @bringyourownai
### Gabriele Santomaggio @gsantomaggio
######################################### 

### do not change this setion ###
info()
{
    echo '[INFO] ' "$@"
}

infoL()
{
    echo -en '[INFO] ' "$@\n"
}

sleep_cursor()
{
 chars="/-\|"
 for (( z=0; z<7; z++ )); do
   for (( i=0; i<${#chars}; i++ )); do
    sleep 0.5
    echo -en "${chars:$i:1}" "\r"
  done
done
}

notes()
{
    echo "$@" >> notes
}

wait() 
{
status=1
infoL "Testing.." $1.$2  
while [ : ]
  do
    sleep_cursor &
    k3 kubectl wait --for condition=ready --timeout=14s pod -l  $1  -n $2
    status=$?
    
    if [ $status -ne 0 ]
    then 
      infoL "$1 isn't ready yet. This may take a few minutes..."
      sleep_cursor
    else
      break  
    fi 
  done
}

#######
install(){
 k3s kubectl create ns jupyter
    k3s kubectl apply -f - << EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-scipy
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-srv
  template:
    metadata:
      labels:
        app: jupyter-srv
    spec:
      containers:
      - name: jupyter-scipy
        image: jupyter/scipy-notebook
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
          name: jupyter
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
EOF
    k3s kubectl apply -f - << EOF
apiVersion: v1
kind: Service
metadata:
  name: jupyter-scipy-service
  namespace: jupyter
spec:
  selector:
    app: jupyter-srv
  ports:
    - name: jupyter
      port: 8888
      targetPort: 8888
  type: LoadBalancer
EOF

    waiting_pod_array=("app=jupyter-srv;jupyter")

    for i in "${waiting_pod_array[@]}"; do 
      echo "$i"; 
      IFS=';' read -ra VALUES <<< "$i"
        wait "${VALUES[0]}" "${VALUES[1]}"
    done


    info "Jupyter Notebook ready!!"

    info "Defining the ingress"
    sleep_cursor

    k3s kubectl apply -f - << EOF
      apiVersion: networking.k8s.io/v1beta1
      kind: IngressClass
      metadata: 
        name: traefik-lb
      spec: 
        controller: traefik.io/ingress-controller
EOF

    k3s kubectl apply -f - << EOF
      apiVersion: "networking.k8s.io/v1beta1"
      kind: "Ingress"
      metadata:
        name: "jupyter-notebook-ingress"
        namespace: jupyter
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
          
      spec:
        ingressClassName: "traefik-lb"
        rules:
        - http:
            paths:
            - path: "/"
              backend:
                serviceName: "jupyter-scipy-notebook"
                servicePort: 8888
EOF
info "Installing KFP SDK"
k3s kubectl exec -n jupyter $(kubectl get pod -n jupyter -l app=jupyter-srv -o name) -- pip install kfp
sleep_cursor

IP=$(kubectl get service/traefik -o jsonpath='{.status.loadBalancer.ingress[0].ip}' -n kube-system)
info "Jupyter Notebook UI ready at: http://"$IP":8888" 
}

install
notes "[plugin_jupyter-scipy]" 
notes "Jupyter Notebook scipy UI: http://"$IP":8888"
#######
